# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='situacao',
        ),
        migrations.AddField(
            model_name='convite',
            name='aceite',
            field=models.BooleanField(default=1),
        ),
    ]
