# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20170925_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='aceite',
            new_name='situacao',
        ),
    ]
