# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20170925_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convite',
            old_name='situacao',
            new_name='aceitar',
        ),
    ]
