# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20170925_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
